#!/bin/bash

# A bash script for managing caddy in conjunction with launchd
# Adapted from apachectl from the Apache Software Foundation
# Copyright (c) 2020 Noel Forté


# util vars
RESET="\033[0m"
BOLD="\033[1m"
RED="\033[31m"
GREEN="\033[32m"
YELLOW="\033[33m"
BLUE="\033[34m"
ARGV="$@"

# main definitions
LAUNCHCTL="/bin/launchctl"
CADDY="/usr/local/bin/caddy"
LAUNCHD_JOB="/Library/LaunchAgents/com.caddy.plist"
CONFIG_PATH="<CADDYFILE_PATH>"

run_launchctl() {
    if [ $UID != 0 ]; then
        echo This operation requires root.
        exit 1
    fi

    $LAUNCHCTL $@
}

case $ARGV in
	start)
		echo -e "${YELLOW}Starting Caddy...${RESET}"
		run_launchctl load -w $LAUNCHD_JOB
		echo -e "${BOLD}${GREEN}Caddy loaded and started.${RESET}"
		exit 0;
		;;
	
	stop)
		echo -e "${YELLOW}Stopping Caddy...${RESET}"
		run_launchctl unload -w $LAUNCHD_JOB
		echo -e "${BOLD}${RED}Caddy unloaded and halted.${RESET}"
		exit 0;
		;;

	reload)
		echo -e "${YELLOW}Reloading Caddy...${RESET}"
		$CADDY reload --config "${CONFIG_PATH}"
		echo -e "${BOLD}${BLUE}Caddy reloaded.${RESET}"
		exit 0;
		;;

	configtest)
		echo -e "${YELLOW}Testing Caddyfile...${RESET}"

	restart)
		echo -e "${BOLD}${YELLOW}Restarting Caddy...${RESET}"
		echo -e "${YELLOW}Stopping Caddy...${RESET}"
		run_launchctl unload -w $LAUNCHD_JOB
		echo -e "${BOLD}${RED}Caddy unloaded and halted.${RESET}"
		echo -e "${YELLOW}Starting Caddy...${RESET}"
		run_launchctl load -w $LAUNCHD_JOB
		echo -e "${BOLD}${GREEN}Caddy loaded and started.${RESET}"
		exit 0;
		;;

	*)
		echo "${YELLOW}Unknown command. Use \"start\" \"stop\" \"reload\" or \"restart\".${RESET}"
		exit 1;
		;;
esac